### ISSUE TITLE
depends on browserify being installed

### ISSUE THREAD

**Issue by Raynos** [dominictarr/demonstrate#2]
```
raynos at raynos-Latitude-E5530-non-vPro in ~/Documents/populate on future*
$ demonstrate README.md > index.html

/home/raynos/Documents/populate/node_modules/demonstrate/index.js:32
    if(err) throw err
                  ^
Error: Command failed: /bin/sh: 1: browserify: not found

    at ChildProcess.exithandler (child_process.js:540:15)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at maybeClose (child_process.js:638:16)
    at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.destroyed (net.js:358:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

It shouldn't depend on global invariants like that.

**Comment by dominictarr** [comment]
fixed in 0.0.3
